NEKO_GIFS = [

       "CgACAgQAAxkBAAICjmGZDeyzTpQJuYQm-1cmEYZvF47GAAK-AAPczSxQDpPNUg2jvFgiBA",

"CgACAgQAAxkBAAICkWGZDvcnG7w0Vd55mtuveRlWEcbwAAKnAgACkrzcUDlIm_J-WDzkIgQ",

"CgACAgQAAxkBAAIClGGZDxQBuO59Ud2rJ54zFdd2wyWMAALWCAACdgeBUkXKrr-N8kZXIgQ",

"CgACAgQAAxkBAAICsGGZDzt-9bEYzycH3mpYQmGm3hA5AAJ1AgACYFeMUumqbyrjC4ttIgQ",

"CgACAgQAAxkBAAICr2GZDzjW37AHtZwoKMlZuTQ_Mu_hAAKgCQAC2HToU22xR4STVnnAIgQ",

"CgACAgIAAxkBAAICrmGZDzicnAt6Fj8zsIw3XrhOyef1AALlCQACncW4SzUlpXSCwy30IgQ",

"CgACAgUAAxkBAAICrWGZDzjtdBZrJ2TGjOsqr_P9s-dvAAIKBAACtzbgVte5Y259JfnZIgQ",

"CgACAgQAAxkBAAICrGGZDzctR9EPAoanIFH2_DYmf2r3AAI0ewACcxpkBz1MO6kOP5tOIgQ",

"CgACAgQAAxkBAAICq2GZDzbxKo0aLUpq3KEhvHRAogoEAAJpAgACA0KsUlUq7sXFvk5hIgQ",

"CgACAgUAAxkBAAICqmGZDzaDwJlLW47GTnbx8Wi3Jl8VAAJbAQACE_URVO4IHQhQRzCbIgQ",

"CgACAgUAAxkBAAICqWGZDzYHv4p2s6mZ98F4R4Mpfd21AAK7BQAC02JQVBry9-tSgCu5IgQ",

"CgACAgQAAxkBAAICqGGZDzYTncKl9OfZP5GX4YVRNOtuAALmBgAC7IDgUMyLor6Ec4_hIgQ",

"CgACAgQAAxkBAAICp2GZDzZ7prrcYm0Q_UZISXZurVU0AAJIAgACNNrdU1YzCUUeF3UcIgQ",

"CgACAgQAAxkBAAICpmGZDzVdbQd1p8-StCBwenKhLr1NAAJ4AgACzt0UU5-G0hQCwshPIgQ",

"CgACAgUAAxkBAAICpWGZDzWSi8cKjRvINqHD4W-gt8qBAAJ3AwACf5g4VGLI1QWcPeLVIgQ",

"CgACAgQAAxkBAAICpGGZDzRg_waN4WIU_sUW5kyRQuSRAAKLAgACQmJ8UgxfVNmtWbyBIgQ",

"CgACAgQAAxkBAAICo2GZDzM_7qFLdm0WGMaMyhMHD-O-AAIkAgACckSVUiGAQggC5DokIgQ",

"CgACAgUAAxkBAAIComGZDzOzoYzlojc6eYk-vdrm0Ha3AALdBAACBDQJVH8q3EnDV328IgQ",

"CgACAgIAAxkBAAICoWGZDzLURXbFzug9qsNTQaaBNX2GAAIUAQACn5fxSdxTsYHCKr83IgQ",

"CgACAgQAAxkBAAICoGGZDzIVXFy8ythsSLPmDjeT1V0zAAJyBQACCus4UIxSf1Jzo7zfIgQ",

"CgACAgQAAxkBAAICn2GZDzHTl36IniNrSC0MtQffRlRXAAKcCQACbqBJUM58QhaqczmlIgQ",

"CgACAgUAAxkBAAICnmGZDzE2IMCDWWerm-NeRtibqse9AALPAwACJ4_xVSq-fGpmVhKBIgQ",

"CgACAgUAAxkBAAICnWGZDzGD8GLWQ7aanq2XP8N_a7HYAAJQAwACO5v5V9MAAWsM9Nh6QiIE",

"CgACAgIAAxkBAAICnGGZDzBrNMbcseqgSun4fD6sg1NDAAKZEgACuF5pS4b3-Q-_Ka7aIgQ",

"CgACAgQAAxkBAAICm2GZDy8T19n3k8gUQKRiTUmAZ2czAAKgCQACZkcJUs4p74V-qbZbIgQ",

"CgACAgIAAxkBAAICmmGZDy_qLUdg8TUUvxjDQm2wEcfHAAKIBwAC4yFJS4dxtyrLj6PiIgQ",

"CgACAgQAAxkBAAICmWGZDy6gCNCgrQfyLiifXLU_bUCNAAI-CwACYHUBU22bIX5ZOG4LIgQ",

"CgACAgQAAxkBAAIDoGGZwX8I-tshRBAXdacYTAWqDw9dAAJbAgAC_MptUG0BEZtCJ7leIgQ",

"CgACAgQAAxkBAAIDnWGZwXDSQPXp5A2rnrUqLEAQKbPvAALhDQACaEnxUjbsjzeH9qv5IgQ",

"CgACAgQAAxkBAAIDmmGZwWBch8hnkNIweLwumwwzdBLoAAJLCgACkthwURks0Lu1yp9jIgQ",

"CgACAgUAAxkBAAIDl2GZwVIBaqQEBcbCPKLYQurDzPekAAL6AANSsAlWaI77q9jADagiBA",

"CgACAgIAAxkBAAIDlGGZwUN5OwZDav7AgOV4-5AXn29pAAL6JQACcpDRS59_U52kTOv8IgQ",

"CgACAgIAAxkBAAIDkWGZwTQU855JgqOQj71hWmc7B0ZbAAJ-BQACQgbBSt_Qcis1setsIgQ",

"CgACAgUAAxkBAAIDjmGZwSipmdvCQ3lSAfty7CkNyG1dAAICAgACxZSwVK6T-8G4N-yVIgQ",

"CgACAgQAAxkBAAIDi2GZwRqYfOn3DbU-01_pU1Dh1wMuAAJPAgACfJu8Uij70Jd9yEv6IgQ",

"CgACAgQAAxkBAAIDgWGZwQqALDGYD-ZJTbdmc4qBbURkAAIkAgAC8beNUvhK5_zTHTgtIgQ",

"CgACAgQAAxkBAAIDcWGZwO-WFsw8GAyvlgJFD0q700svAAJWAgACvpZsUAituvCFvoYtIgQ",

"CgACAgIAAxkBAAIDRmGZwJfoxkB-X6WKRG_tBpTty_QYAAIfBwAC3MkYSjATMcr_Dg9XIgQ",

"CgACAgQAAxkBAAIDQ2GZwIn9KWKLwSVkh3UJmEwx7OhRAAJ9CQACpOhpUqZkj-mIb5L3IgQ",

"CgACAgEAAxkBAAIDP2GZwHKRFT9Ky7YcMiBrhW7B0ItQAALTAAM4igFFNO1IauHbH1ciBA",

"CgACAgUAAxkBAAIDO2GZwGJcAyWp0kZNyO1QvbjftF2iAAKgAQACIPLYV01TUC4V84sSIgQ",

"CgACAgQAAxkBAAIDNmGZwFWwYXKbn5og3n0Y-q13L4M-AAIoAgACgKfkUsqhRZbVebLOIgQ",

"CgACAgQAAxkBAAIDMGGZwEdwr6eQd8AUezMy9us17S3mAAKgAgACnOE9U_YxjX7elrs4IgQ",

"CgACAgQAAxkBAAIDLWGZwD0h5ZE9Rx2_M2gr6eInlFixAAIWBwACl0NAUyNYxPUxjC4BIgQ",

"CgACAgIAAxkBAAIDKWGZwDEIpGFBvZGHaM3B3PiUw5WCAAI1AwACHGtBSKRQLVGkYnEoIgQ",

"CgACAgIAAxkBAAIDJmGZwCKUvVHjWcJmbGAknlKdPWY_AALtDAACIYnJSIHHdYsHuy2aIgQ",

"CgACAgQAAxkBAAIDI2GZwBEUOOV79ZHLyzbybHEHNQTpAAJlAwACmiO4UHsC6ohLEVv9IgQ"

 ]

NEKO_TEXT = [

     "@nyagurl, the Neko, Scratches you!",

     "Nya! {user1} is a Neko!",

     "My Heart Goes Meow😻",

     "Neko Neko Niii!"

     "{user1} nyaed {user2}"

   ]

CATTO_GIFS = [

     "CgACAgQAAxkBAAIDSWGZwL91bBG-jZ_egpq5OuyuAipsAAJ9BQACKkOxUH4wXhjT8HbOIgQ",

"CgACAgQAAxkBAAIDSmGZwL-RN3IBlJTBUjlqd3pXk6QqAALGBAACRuvYU2WBgr_1C_0TIgQ",

"CgACAgUAAxkBAAIDS2GZwL9B97dax30-lc2ACMci0FKJAAJkBAACWPRAVyqU3IdRJhGeIgQ",

"CgACAgEAAxkBAAIDTGGZwL-XA0lwXrriPr_zt4v-IPkfAAK6AQACwQ-pRpjjoSho_RE9IgQ",

"CgACAgUAAxkBAAIDTWGZwL-Y-hIyYnMg7mnxpAllNBo9AAIlBQAC-4K5VwuhvkPt2YP9IgQ",

"CgACAgQAAxkBAAIDTmGZwL9DAAHWnS0D7EnUljPuAo--xAACbwIAAmEd9VD8XLWo8TdFQSIE",

"CgACAgEAAxkBAAIDT2GZwL8rJc4MxmbVUbYRFB_YxKRHAAIoAQAC99zwRC2DaHXTI7KoIgQ",

"CgACAgIAAxkBAAIDUGGZwL_-XQfAp5RKUhnzeX2xT0QeAAKWBgAC3oEwSqY1y5fxhkaVIgQ",

"CgACAgQAAxkBAAIDUWGZwL8stOKlG1ApKx62HwZGoewaAAIwAgACDdnFUuWhnjKjQAmBIgQ",

"CgACAgQAAxkBAAIDUmGZwL8zH3GNxrYChtpnicmDLatOAAKcBgACQN5wUQw7y8DphVjcIgQ",

"CgACAgIAAxkBAAIDU2GZwL8G3JTQGOBr_Cdcv6sDspJGAALxCwACd41wSEI4zMHuNtZmIgQ",

"CgACAgQAAxkBAAIDVGGZwL-rLpsmmxPcsB5EYVVRG1NrAAItCwACGXAYUeYyV77j0HPBIgQ",

"CgACAgUAAxkBAAIDVWGZwL8vbrlynYEs8vRImvW1iSVIAALAAwAC0z6AVJF9KYTu12ooIgQ",

"CgACAgQAAxkBAAIDVmGZwL9r-iARXzVUQvEK37ZT149kAAK6AQACK3UVUwJ9Sqh2SNZHIgQ",

"CgACAgIAAxkBAAIDV2GZwL9T_HT0eAABlcqZ6b4BnD8c4gACXgYAAk4IUEsmz4Zo_WctQiIE",

"CgACAgUAAxkBAAIDWGGZwL-wx6nx0tz2CSCpMmWQxJArAAJ0AwACR4IIVxhiXwMhGjXUIgQ",

"CgACAgQAAxkBAAIDWWGZwL83TRt1B3qL1qdQcwMal64SAAI0AgAD_fxSufUrQDtJS4IiBA",

"CgACAgIAAxkBAAIDWmGZwL8dAe-Rg8aNQCqR5t6EHXX0AAL1CAAC2ZixSOYrAoNvc5-mIgQ",

"CgACAgQAAxkBAAIDW2GZwL9cFiTb34QmAQ7v2ooJwEA4AAIEAwAC-aeIU2qBX8P1OcMwIgQ",

"CgACAgIAAxkBAAIDXGGZwL8rSQ6jTqumqdjqIviJrwTaAAKfCwACHLqoSKzFzuF39HMwIgQ",

"CgACAgUAAxkBAAIDpGGZws7sz4S9hJ-rv0XUSzZwzp2YAAJ0AwACR4IIVxhiXwMhGjXUIgQ",

"CgACAgQAAxkBAAIDp2GZwuSEwnZFSFAxfV9jPiccnQFNAAJOAgACz8yFUum0xTWFhpmtIgQ",

"CgACAgQAAxkBAAIDqmGZwwzAJbhfAWuLGW1AkAPCiV3CAAJJAgACB3mUUvFMUpbUJlyHIgQ",

"CgACAgQAAxkBAAIDq2GZwwyIrNbgEVX1vG-Hi2zQ8w3RAAKeCAACTXHQUqjZqHzJpwjnIgQ",

"CgACAgUAAxkBAAIDrGGZwww3X3QE0A4L0yFfPD3BUd2AAAKxAgACJ2s5V9y3oA253XzpIgQ",

"CgACAgUAAxkBAAIDrWGZwwwnbfri_Rlu3qL5WqtHGOOOAAL6AgACtCU4V26utRYZcxssIgQ",

"CgACAgQAAxkBAAIDrmGZwwwYyNapugABzc28hyQqY5y4qwACGgMAAhAPbFIzFj7i8sIk6iIE",

"CgACAgIAAxkBAAIDr2GZwwyUWMJzL3JDvPiIp8PAsJrIAAIXAANoVNFL2u1-y5dyxeUiBA",

"CgACAgQAAxkBAAIDsGGZwwyXyxznpA2b6eWPfUSD1SW1AAJ5AgACaz6UUkB4nb25lLjiIgQ",

"CgACAgQAAxkBAAIDsWGZwwztvljZE1m-WNILUX6BxRBJAALpAAPZ8EBThTSY7bxlUj0iBA",

"CgACAgUAAxkBAAIDsmGZwwwuFrO8J7Va_aGADEluHVpCAAK7AQACvIDJVKgTEAixCv8DIgQ",

"CgACAgQAAxkBAAIDs2GZwwwlS6EDGTYWtJ_RMMAtxR0CAAJwAgAC-BEFUND2W6Jso3LyIgQ",

"CgACAgQAAxkBAAIDtGGZwwyu7ATzgEQgf1XM7ufNrJcKAALWAgACsf_EUUQkntosXyjDIgQ",

"CgACAgUAAxkBAAIDtWGZwwyykuvNyT1LA6K4iZr3gnTKAAIyAANdmIFVo2pr5o8ihiIiBA",

"CgACAgQAAxkBAAIDtmGZwwzH2sb89_MJhM8xq9EuTexYAAJAAgACoNmFUrDgiXfsf9fzIgQ",

"CgACAgIAAxkBAAIDt2GZwwx9AAEnz75njZbDo3lC9SRUeQAC9wEAAvGGAUmmhTmGYxvciSIE",

"CgACAgUAAxkBAAIDuGGZwwxCpOnydm-E5oq-ZaUjlrOTAAKFAwACnmE5VoUkMkIuDESMIgQ",

"CgACAgIAAxkBAAIDuWGZwwwXhrhkoSIKtgIFlKad3qTDAAKxCQAC7O0wSIBzEd6lOnjBIgQ",

"CgACAgUAAxkBAAIDumGZwwxBL3dWruVoZhahmWImcgO5AAJhAQACXTIBVshsfbOACWStIgQ",

"CgACAgQAAxkBAAIDu2GZwwys9KLBG2NRrxsOEyipVFR3AAIvAwACD84UUhv84MLdHF_xIgQ",

"CgACAgQAAxkBAAIDvGGZwwzIaHqeDhIrowyBqNhmYx5fAAI1BwACGExpU3iT4SWiI8pOIgQ",

"CgACAgQAAxkBAAIDvWGZwwwT4GQ7n_zgiT0YhI7cXw73AAIyAgACYt79Ujm46IpemwABoCIE",

"CgACAgQAAxkBAAIDvmGZwwx_qjbVZ3vwKEWPONDirIcBAAJiAgACUXxMUfEjoQio2NkkIgQ",

"CgACAgEAAxkBAAIDv2GZwwwhmtZuziBiEAghLL02z25_AAIcAQAC3bAxR9xnHtHIPH8nIgQ",

"CgACAgEAAxkBAAIDwGGZwwzvnmXgCQ2oa9fTWMJ7A0IPAAJXAAO5xYBH2nEJeRDU0KsiBA",

"CgACAgQAAxkBAAIDwWGZwwy99Mhn1S7DQvx7Ke-9j0u8AAJEAgAC93RMU4RF1MNKHaoUIgQ",

"CgACAgQAAxkBAAIDwmGZwwzghUFwWbjDHFJBv60KneU1AAIxAgACSl-dUkIj0uun-spBIgQ"

     

     

     

     

     

     

     

     

      ]

CATTO_TEXT = [

      "Cat Is Sleeping Nya!",

      "Catto Just Scratched you",

      "@nyagurl is the Catto Lord",

      "Catto is playing with @TheSidharthaRao now!",

      "Catto Loves You ❤"

    ]
